import db from '@/lib/db';

export async function GET(request) {
    try {
        const { searchParams } = new URL(request.url);
        const filter = searchParams.get('filter'); // 'all' or 'YYYY-MM'
        const dateStr = searchParams.get('date'); // YYYY-MM-DD

        let start, end;

        // Determine Date Range
        if (filter === 'all') {
            start = '1970-01-01';
            end = '2099-12-31';
        } else if (filter && filter.match(/^\d{4}-\d{2}$/)) {
            const [y, m] = filter.split('-');
            const d = new Date(parseInt(y), parseInt(m) - 1, 1);
            start = d.toISOString().split('T')[0];
            // Ensure End Date includes the full day
            end = end + ' 23:59:59';
            start = start + ' 00:00:00';
        }

        // 1. Total Investment (Cost of Goods Purchased in this period)
        const investResult = await db.execute({
            sql: `SELECT SUM(quantity * buy_price) as total_invest 
                  FROM stock_logs 
                  WHERE created_at >= ? AND created_at <= ?`,
            args: [start, end]
        });

        // 2. Revenue & Profit (From Sales generated by batches bought in this period)
        const salesResult = await db.execute({
            sql: `SELECT 
                    SUM(sba.quantity * si.price_at_sale) as total_revenue,
                    SUM(sba.quantity * (si.price_at_sale - sl.buy_price)) as total_profit
                  FROM sale_batch_allocations sba
                  JOIN stock_logs sl ON sba.stock_log_id = sl.id
                  JOIN sale_items si ON sba.sale_item_id = si.id
                  WHERE sl.created_at >= ? AND sl.created_at <= ?`,
            args: [start, end]
        });

        return new Response(JSON.stringify({
            invest: investResult.rows[0]?.total_invest || 0,
            revenue: salesResult.rows[0]?.total_revenue || 0,
            profit: salesResult.rows[0]?.total_profit || 0
        }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' }
        });
    } catch (error) {
        console.error('Investment Stats Error:', error);
        return new Response(JSON.stringify({ error: 'Failed to fetch investment stats' }), { status: 500 });
    }
}
